(function(){
  'use strict';
  const E={metric:'weight_kg',period:'all',a:null,b:null,historyOpen:null};
  const METRICS={
    weight_kg:{label:'Peso',unit:'kg',digits:1},
    skeletal_muscle_mass_kg:{label:'Massa muscular esquelética',unit:'kg',digits:1},
    fat_mass_kg:{label:'Massa de gordura',unit:'kg',digits:1},
    body_fat_pct:{label:'Percentual de gordura registrado',unit:'%',digits:1},
    body_water_l:{label:'Água corporal',unit:'L',digits:1},
    visceral_fat_level:{label:'Gordura visceral · nível',unit:'',digits:0},
    score:{label:'Score InBody',unit:'',digits:0},
    waist_hip_ratio:{label:'Cintura/quadril',unit:'',digits:2},
    bmr_kcal:{label:'TMB registrada',unit:'kcal/dia',digits:0}
  };
  const day=v=>String(v||'').slice(0,10);
  const num=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
  const safe=v=>esc(v??'');
  const body=()=>[...(state.body||[])].filter(x=>x.measured_at).sort((a,b)=>String(a.measured_at).localeCompare(String(b.measured_at)));
  const seg=()=>[...(state.segmental||[])].filter(x=>x.measured_at).sort((a,b)=>String(a.measured_at).localeCompare(String(b.measured_at)));
  const cutoff=period=>{if(period==='all')return null;const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-Number(period)+1);return d.toISOString().slice(0,10)};
  const filtered=()=>{const c=cutoff(E.period);return body().filter(x=>!c||day(x.measured_at)>=c)};
  const fmt=(v,m)=>{v=num(v);if(v==null)return'—';return `${fmtNum(v,m.digits)}${m.unit?' '+m.unit:''}`};
  const delta=(a,b,m)=>{a=num(a);b=num(b);if(a==null||b==null)return'—';const d=a-b;return`${d>0?'+':''}${fmtNum(d,m.digits)}${m.unit?' '+m.unit:''}`};
  function chart(rows,key){
    const m=METRICS[key],pts=rows.map(r=>({d:day(r.measured_at),v:num(r[key])})).filter(x=>x.v!=null);if(pts.length<2)return'<div class="epEmpty">São necessários pelo menos dois pontos numéricos para desenhar a série.</div>';
    const w=920,h=260,p=34,min0=Math.min(...pts.map(x=>x.v)),max0=Math.max(...pts.map(x=>x.v)),pad=(max0-min0||Math.max(Math.abs(max0),1))*.08,min=min0-pad,max=max0+pad,span=max-min||1,x=i=>p+i*(w-p*2)/Math.max(1,pts.length-1),y=v=>p+(max-v)*(h-p*2)/span,path=pts.map((z,i)=>`${i?'L':'M'}${x(i).toFixed(1)} ${y(z.v).toFixed(1)}`).join(' ');
    const grid=[0,.25,.5,.75,1].map(t=>{const yy=p+t*(h-p*2),val=max-t*span;return`<g><line x1="${p}" x2="${w-p}" y1="${yy}" y2="${yy}"/><text x="4" y="${yy+3}">${safe(fmtNum(val,m.digits))}</text></g>`}).join('');
    return `<div class="epChartWrap"><svg class="epChart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><g class="grid">${grid}</g><path d="${path}" class="line"/>${pts.map((z,i)=>`<circle cx="${x(i).toFixed(1)}" cy="${y(z.v).toFixed(1)}" r="4"><title>${fmtDate(z.d)} · ${fmt(z.v,m)}</title></circle>`).join('')}</svg></div><div class="epAxis"><span>${fmtDate(pts[0].d)}</span><span>${pts.length} pontos com valor</span><span>${fmtDate(pts.at(-1).d)}</span></div>`;
  }
  function snapshotCard(label,key,row){const m=METRICS[key];return`<div class="epMetric"><span>${safe(label)}</span><strong>${fmt(row?.[key],m)}</strong><small>${row?fmtDate(row.measured_at):'sem registro'}</small></div>`}
  function compare(){
    const rows=body();if(!rows.length)return'<div class="epEmpty">Sem medições corporais estruturadas.</div>';const a=rows.find(r=>day(r.measured_at)===E.a)||rows.at(-1),b=rows.find(r=>day(r.measured_at)===E.b)||rows.at(-2)||rows.at(-1);E.a=day(a.measured_at);E.b=day(b.measured_at);
    const opts=rows.slice().reverse().map(r=>`<option value="${day(r.measured_at)}">${fmtDate(r.measured_at)}</option>`).join('');
    const keys=['weight_kg','skeletal_muscle_mass_kg','fat_mass_kg','body_fat_pct','body_water_l','visceral_fat_level','score','waist_hip_ratio','bmr_kcal'];
    return `<div class="epCompareHead"><div><b>Comparar duas medições</b><small>Diferenças são descritivas e não classificam aparência, desempenho ou saúde.</small></div></div><div class="epCompareControls"><label>A · medição mais recente<select id="epA">${opts}</select></label><label>B · referência<select id="epB">${opts}</select></label></div><div class="epCompareTable"><div class="epCompareRow head"><span>Métrica</span><span>A</span><span>B</span><span>A − B</span></div>${keys.map(k=>{const m=METRICS[k];return`<div class="epCompareRow"><span>${safe(m.label)}</span><strong>${fmt(a[k],m)}</strong><strong>${fmt(b[k],m)}</strong><strong>${delta(a[k],b[k],m)}</strong></div>`}).join('')}</div>`;
  }
  function segmental(){
    const rows=seg();if(!rows.length)return'<div class="epEmpty">Sem análise segmentar estruturada.</div>';const cur=rows.at(-1),prev=rows.at(-2),parts=[
      ['Braço direito','lean_right_arm_kg','fat_right_arm_kg'],['Braço esquerdo','lean_left_arm_kg','fat_left_arm_kg'],['Tronco','lean_trunk_kg','fat_trunk_kg'],['Perna direita','lean_right_leg_kg','fat_right_leg_kg'],['Perna esquerda','lean_left_leg_kg','fat_left_leg_kg']
    ];
    return `<div class="epSegmentHead"><div><b>Composição segmentar</b><small>${fmtDate(cur.measured_at)}${prev?` comparada a ${fmtDate(prev.measured_at)}`:''}. Valores D/E são apresentados sem transformar diferença em julgamento corporal.</small></div><span>${rows.length} medições segmentares</span></div><div class="epSegmentGrid">${parts.map(([label,lean,fat])=>{const lv=num(cur[lean]),fv=num(cur[fat]),pl=num(prev?.[lean]),pf=num(prev?.[fat]);return`<div class="epSegment"><b>${safe(label)}</b><div><span>Massa magra</span><strong>${lv!=null?fmtNum(lv,2)+' kg':'—'}</strong><small>${prev&&pl!=null&&lv!=null?`dif. ${lv-pl>0?'+':''}${fmtNum(lv-pl,2)} kg`:'sem comparação'}</small></div><div><span>Gordura registrada</span><strong>${fv!=null?fmtNum(fv,2)+' kg':'—'}</strong><small>${prev&&pf!=null&&fv!=null?`dif. ${fv-pf>0?'+':''}${fmtNum(fv-pf,2)} kg`:'sem comparação'}</small></div></div>`}).join('')}</div>`;
  }
  function history(){const rows=body().slice().reverse();return `<div class="epHistory">${rows.map(r=>{const id=day(r.measured_at),open=E.historyOpen===id;return`<article class="epHistoryItem ${open?'open':''}" data-ep-history="${id}"><button type="button"><time>${fmtDate(r.measured_at)}</time><div><b>${fmt(r.weight_kg,METRICS.weight_kg)} · ${fmt(r.skeletal_muscle_mass_kg,METRICS.skeletal_muscle_mass_kg)}</b><small>${safe(r.source||'fonte não informada')} · confiança ${safe(r.confidence||'não classificada')}</small></div><span>${open?'fechar':'detalhes'}</span></button><div class="epHistoryDetail"><div>${snapshotCard('Peso','weight_kg',r)}${snapshotCard('Massa muscular','skeletal_muscle_mass_kg',r)}${snapshotCard('Massa de gordura','fat_mass_kg',r)}${snapshotCard('% gordura registrado','body_fat_pct',r)}${snapshotCard('Água corporal','body_water_l',r)}${snapshotCard('Visceral','visceral_fat_level',r)}${snapshotCard('Score','score',r)}${snapshotCard('Cintura/quadril','waist_hip_ratio',r)}${snapshotCard('TMB','bmr_kcal',r)}</div><p>Fonte: ${safe(r.source||'—')}${r.source_file?` · arquivo: ${safe(r.source_file)}`:''}. Notas livres da fonte ficam preservadas no banco, mas esta visão usa somente os valores estruturados.</p></div></article>`}).join('')}</div>`}
  function render(){
    const root=q('productEvolution');if(!root)return;const rows=filtered(),all=body(),latest=all.at(-1),previous=all.at(-2),m=METRICS[E.metric],first=rows.find(r=>num(r[E.metric])!=null),last=[...rows].reverse().find(r=>num(r[E.metric])!=null),d=first&&last&&first!==last?delta(last[E.metric],first[E.metric],m):'—';
    root.innerHTML=`<div class="epTitle"><div><div class="epKicker">COMPOSIÇÃO CORPORAL</div><h1>Evolução</h1><p>Histórico completo, comparação entre datas e composição segmentar usando apenas medições registradas.</p></div><button class="productBtn primary" id="epAdd">Registrar bioimpedância</button></div><div class="epCurrent"><div class="epCurrentMain"><span>Última medição</span><strong>${latest?fmtDate(latest.measured_at):'—'}</strong><small>${safe(latest?.source||'sem fonte registrada')}</small></div>${snapshotCard('Peso','weight_kg',latest)}${snapshotCard('Massa muscular','skeletal_muscle_mass_kg',latest)}${snapshotCard('Massa de gordura','fat_mass_kg',latest)}${snapshotCard('% gordura registrado','body_fat_pct',latest)}</div><div class="epPanel"><div class="epPanelHead"><div><b>Série longitudinal</b><small>Selecione uma métrica e um período. O eixo usa somente valores observados.</small></div><div class="epControls"><select id="epMetric">${Object.entries(METRICS).map(([k,v])=>`<option value="${k}" ${k===E.metric?'selected':''}>${safe(v.label)}</option>`).join('')}</select><select id="epPeriod"><option value="365" ${E.period==='365'?'selected':''}>1 ano</option><option value="730" ${E.period==='730'?'selected':''}>2 anos</option><option value="all" ${E.period==='all'?'selected':''}>Todo histórico</option></select></div></div><div class="epChartStats"><div><span>Primeiro ponto no filtro</span><strong>${first?fmt(first[E.metric],m):'—'}</strong><small>${first?fmtDate(first.measured_at):'—'}</small></div><div><span>Último ponto no filtro</span><strong>${last?fmt(last[E.metric],m):'—'}</strong><small>${last?fmtDate(last.measured_at):'—'}</small></div><div><span>Diferença observada</span><strong>${d}</strong><small>último − primeiro</small></div><div><span>Medições no filtro</span><strong>${rows.length}</strong><small>${all.length} no histórico completo</small></div></div>${chart(rows,E.metric)}</div><div class="epGrid"><section class="epPanel">${compare()}</section><section class="epPanel">${segmental()}</section></div><div class="epPanel epHistoryPanel"><div class="epPanelHead"><div><b>Histórico de medições</b><small>Valores estruturados e proveniência. Notas livres da fonte não são usadas para classificar o corpo.</small></div><span>${all.length} registros</span></div>${history()}</div>`;
    q('epAdd').onclick=()=>q('v14AddBody')?.click();q('epMetric').onchange=e=>{E.metric=e.target.value;render()};q('epPeriod').onchange=e=>{E.period=e.target.value;render()};q('epA').value=E.a;q('epB').value=E.b;q('epA').onchange=e=>{E.a=e.target.value;render()};q('epB').onchange=e=>{E.b=e.target.value;render()};root.querySelectorAll('[data-ep-history]>button').forEach(b=>b.onclick=()=>{const id=b.parentElement.dataset.epHistory;E.historyOpen=E.historyOpen===id?null:id;render()});
  }
  const prior=loadAll;loadAll=async function(){const out=await prior();render();return out};
  sb.auth.getSession().then(({data})=>{if(data?.session)setTimeout(render,1950)});
})();
