(function(){
  'use strict';
  const S={type:'all',query:''};
  const day=v=>String(v||'').slice(0,10);
  const norm=v=>String(v||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').trim();
  const safe=v=>esc(v??'');
  function rows(){const out=[];
    for(const w of state.canonicalWorkouts||[])out.push({type:'Treino',kind:'training',date:day(w.workout_date),title:w.workout_type||'Treino',sub:[w.location,w.record_status==='review_required'?'registro parcial':null].filter(Boolean).join(' · '),source:w.source||'',target:'training'});
    for(const e of state.exercises||[])out.push({type:'Exercício',kind:'training',date:day(e.workout_date),title:e.exercise||'Exercício',sub:[e.muscle_group,e.machine].filter(Boolean).join(' · '),source:e.source||'',target:'training'});
    for(const b of state.body||[])out.push({type:'Composição',kind:'body',date:day(b.measured_at),title:'Composição corporal',sub:[b.weight_kg!=null?fmtNum(b.weight_kg,1)+' kg':null,b.skeletal_muscle_mass_kg!=null?'massa muscular '+fmtNum(b.skeletal_muscle_mass_kg,1)+' kg':null].filter(Boolean).join(' · '),source:b.source_file||b.source||'',target:'evolution'});
    for(const l of state.labs||[])out.push({type:'Exame',kind:'labs',date:day(l.collection_date),title:l.biomarker||'Biomarcador',sub:[l.result_raw,l.unit,l.laboratory].filter(Boolean).join(' · '),source:l.source_file||l.source||'',target:'health'});
    for(const d of state.docs||[])out.push({type:'Documento',kind:'docs',date:day(d.document_date),title:d.title||d.document_type||'Documento',sub:d.document_type||'',source:d.source_file||d.source||'',target:'health'});
    return out.filter(x=>x.date).sort((a,b)=>b.date.localeCompare(a.date)||a.title.localeCompare(b.title,'pt-BR'));
  }
  function latestSuggestions(all){const seen=new Set(),out=[];for(const r of all){const k=r.kind+':'+r.date+':'+r.title;if(seen.has(k))continue;seen.add(k);out.push(r);if(out.length>=10)break}return out}
  function resultHtml(r){return `<button type="button" class="spResult" data-sp-target="${safe(r.target)}"><time>${fmtDate(r.date)}</time><div><div class="spResultTop"><b>${safe(r.title)}</b><span>${safe(r.type)}</span></div><p>${safe(r.sub||'registro preservado')}</p><small>${r.source?'Fonte: '+safe(r.source):'Fonte não registrada'}</small></div><i>›</i></button>`}
  function render(){const box=q('commandSearchResults');if(!box)return;const all=rows(),term=norm(S.query),filtered=all.filter(r=>(S.type==='all'||r.kind===S.type)&&(!term||norm(`${r.type} ${r.title} ${r.sub} ${r.source}`).includes(term))),items=term?filtered.slice(0,100):latestSuggestions(filtered);box.innerHTML=`<div class="spMeta"><span>${term?`${filtered.length} resultado(s)`:'Registros recentes'}</span><small>${term?'Busca em treino, composição, exames e documentos':'Digite para pesquisar todo o índice estrutural carregado'}</small></div><div class="spList">${items.map(resultHtml).join('')||'<div class="spEmpty">Nenhum registro corresponde à busca.</div>'}</div>`;box.querySelectorAll('[data-sp-target]').forEach(b=>b.onclick=()=>{activateTab(b.dataset.spTarget);close();});}
  function close(){q('productSearchModal')?.classList.add('hidden')}
  function install(){const old=q('productSearchModal');if(old)old.remove();const m=document.createElement('div');m.id='productSearchModal';m.className='productSearchModal hidden spModal';m.innerHTML=`<div class="spSheet"><div class="spHead"><div><div class="spKicker">BUSCA GLOBAL</div><b>Encontre qualquer registro</b><small>Treinos, exercícios, composição, exames e documentos.</small></div><button type="button" data-sp-close>×</button></div><div class="spSearch"><span>⌕</span><input id="productSearchInput" type="search" autocomplete="off" placeholder="Buscar exercício, biomarcador, local, documento…"><kbd>esc</kbd></div><div class="spTypes"><button data-sp-type="all" class="active">Tudo</button><button data-sp-type="training">Treino</button><button data-sp-type="body">Composição</button><button data-sp-type="labs">Exames</button><button data-sp-type="docs">Documentos</button></div><div id="commandSearchResults"></div><div class="spFoot">Enter não altera dados. Resultados apenas navegam para a área correspondente; a proveniência continua preservada no registro original.</div></div>`;document.body.appendChild(m);m.onclick=e=>{if(e.target===m||e.target.closest('[data-sp-close]'))close()};q('productSearchInput').oninput=e=>{S.query=e.target.value;render()};m.querySelectorAll('[data-sp-type]').forEach(b=>b.onclick=()=>{S.type=b.dataset.spType;m.querySelectorAll('[data-sp-type]').forEach(x=>x.classList.toggle('active',x===b));render()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!m.classList.contains('hidden')){e.preventDefault();close()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();m.classList.remove('hidden');setTimeout(()=>q('productSearchInput')?.focus(),20)}});render();
  }
  install();
  const prior=loadAll;loadAll=async function(){const out=await prior();render();return out};
})();
