(function(){
  'use strict';
  const TL={days:'90',type:'all',query:'',source:'all',limit:36,loading:false,loaded:false,nutrition:[],metrics:[],activity:[]};
  const day=v=>String(v||'').slice(0,10);
  const norm=v=>String(v||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').trim();
  const num=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
  const safe=v=>esc(v??'');
  const unique=a=>[...new Set(a.filter(Boolean))];
  const cutoff=days=>{if(days==='all')return null;const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-Number(days)+1);return d.toISOString().slice(0,10)};
  const inDays=(v,days)=>days==='all'||day(v)>=cutoff(days);
  const mean=a=>{const x=a.map(num).filter(v=>v!=null);return x.length?x.reduce((s,v)=>s+v,0)/x.length:null};
  async function fetchPaged(table,select,order,max){const out=[];let from=0;const size=900;while(from<max){let qy=sb.from(table).select(select);if(order)qy=qy.order(order,{ascending:true});const r=await qy.range(from,Math.min(from+size-1,max-1));if(r.error)throw r.error;out.push(...(r.data||[]));if(!r.data||r.data.length<size)break;from+=size}return out}
  async function load(){if(TL.loading||!currentSession?.user)return;TL.loading=true;try{const [n,m,a]=await Promise.all([
    fetchPaged('health_daily_nutrition','nutrition_date,calories_kcal,protein_g,carbs_g,fat_g,source,confidence','nutrition_date',5000),
    fetchPaged('health_metrics','measured_at,metric_type,value,unit,source,confidence','measured_at',12000),
    fetchPaged('health_activity_records','activity_date,activity_name,activity_type,calories_kcal,duration_minutes,steps,source,confidence,record_status,is_adjustment','activity_date',9000)
  ]);TL.nutrition=n;TL.metrics=m;TL.activity=a;TL.loaded=true}catch(e){console.error('timeline product load',e);TL.error=e?.message||String(e)}finally{TL.loading=false;render()}}
  function confidence(c){const x=norm(c);if(!x)return'';if(x.includes('high')||x.includes('valid'))return'alta confiança';if(x.includes('medium'))return'confiança média';if(x.includes('low'))return'baixa confiança';return String(c)}
  function event(type,date,title,sub,source,confidenceValue,target,kind){return{type,date:day(date),title,sub,source:source||'',confidence:confidenceValue||'',target,kind:kind||type}}
  function build(){const out=[];
    for(const w of state.canonicalWorkouts||[])out.push(event('Treino',w.workout_date,w.workout_type||'Treino',[w.location,w.record_status==='review_required'?'registro parcial':null].filter(Boolean).join(' · '),w.source,w.confidence,'training','training'));
    for(const b of state.body||[])out.push(event('Composição',b.measured_at,'Composição corporal',[b.weight_kg!=null?fmtNum(b.weight_kg,1)+' kg':null,b.skeletal_muscle_mass_kg!=null?'massa muscular '+fmtNum(b.skeletal_muscle_mass_kg,1)+' kg':null,b.body_fat_pct!=null?'gordura registrada '+fmtNum(b.body_fat_pct,1)+'%':null].filter(Boolean).join(' · '),b.source_file||b.source,b.confidence,'evolution','body'));
    const labsByDate=new Map();for(const r of state.labs||[]){const d=day(r.collection_date);if(!d)continue;const g=labsByDate.get(d)||[];g.push(r);labsByDate.set(d,g)}for(const [d,rows] of labsByDate){out.push(event('Exames',d,'Coleta laboratorial',`${rows.length} resultado(s) · ${unique(rows.map(r=>r.biomarker)).length} biomarcador(es)`,rows[0]?.laboratory||rows[0]?.source,rows[0]?.confidence,'health','labs'))}
    for(const d of state.docs||[])out.push(event('Documento',d.document_date,d.title||d.document_type||'Documento',d.document_type||'metadado de documento',d.source_file||d.source,d.confidence,'health','document'));
    const nutrition=TL.loaded?TL.nutrition:(state.nutrition||[]);for(const n of nutrition)out.push(event('Nutrição',n.nutrition_date,'Nutrição registrada',[num(n.calories_kcal)!=null?fmtNum(n.calories_kcal,0)+' kcal':null,num(n.protein_g)!=null?'proteína '+fmtNum(n.protein_g,0)+' g':null].filter(Boolean).join(' · '),n.source,n.confidence,'nutrition','nutrition'));
    const metricRows=TL.loaded?TL.metrics:(state.metrics||[]),metricsByDate=new Map();for(const m of metricRows){const d=day(m.measured_at);if(!d)continue;const g=metricsByDate.get(d)||[];g.push(m);metricsByDate.set(d,g)}for(const [d,rows] of metricsByDate){const names=unique(rows.map(r=>r.metric_type)),parts=[];const sleep=rows.find(r=>r.metric_type==='sleep_duration_h'),energy=rows.find(r=>r.metric_type==='active_energy_kcal'),exercise=rows.find(r=>r.metric_type==='exercise_minutes'),stand=rows.find(r=>r.metric_type==='stand_hours');if(num(sleep?.value)!=null)parts.push('sono '+fmtNum(sleep.value,1)+' h');if(num(energy?.value)!=null)parts.push('energia ativa '+fmtNum(energy.value,0)+' kcal');if(num(exercise?.value)!=null)parts.push('exercício '+fmtNum(exercise.value,0)+' min');if(num(stand?.value)!=null)parts.push('em pé '+fmtNum(stand.value,0)+' h');if(parts.length||names.length)out.push(event('Atividade & sono',d,'Atividade e recuperação registradas',parts.join(' · ')||`${names.length} métrica(s)`,unique(rows.map(r=>r.source)).join(', '),rows[0]?.confidence,'health','metrics'))}
    const activity=TL.loaded?TL.activity:[],actByDate=new Map();for(const a of activity){if(a.record_status==='quarantined'||a.is_adjustment)continue;const d=day(a.activity_date);if(!d)continue;const g=actByDate.get(d)||[];g.push(a);actByDate.set(d,g)}for(const [d,rows] of actByDate){const mins=rows.map(r=>num(r.duration_minutes)).filter(v=>v!=null).reduce((s,v)=>s+v,0),kcal=rows.map(r=>num(r.calories_kcal)).filter(v=>v!=null).reduce((s,v)=>s+v,0);const parts=[`${rows.length} registro(s)`];if(mins)parts.push(fmtNum(mins,0)+' min registrados');if(kcal)parts.push(fmtNum(kcal,0)+' kcal registradas');out.push(event('Atividade',d,'Atividade importada',parts.join(' · '),unique(rows.map(r=>r.source)).join(', '),rows[0]?.confidence,'health','activity'))}
    for(const ql of state.quality||[]){if(String(ql.status||'').toLowerCase()!=='open')continue;const d=day(ql.detected_at);if(!d)continue;out.push(event('Qualidade',d,ql.entity_name||'Revisão de dados',ql.description||ql.issue_code,ql.source_file||'ledger de qualidade',null,'inbox','quality'))}
    return out.filter(x=>x.date).sort((a,b)=>b.date.localeCompare(a.date)||String(a.type).localeCompare(String(b.type),'pt-BR'));
  }
  function sourceOptions(events){const values=unique(events.map(e=>e.source).filter(Boolean)).sort((a,b)=>String(a).localeCompare(String(b),'pt-BR'));return values}
  function typeClass(t){const x=norm(t);if(x.includes('treino'))return'train';if(x.includes('compos'))return'body';if(x.includes('nutri'))return'nut';if(x.includes('exam'))return'lab';if(x.includes('doc'))return'doc';if(x.includes('qual'))return'quality';return'activity'}
  function monthLabel(d){const dt=new Date(d+'T12:00:00');return dt.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}
  function dayLabel(d){const dt=new Date(d+'T12:00:00');return dt.toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'}).replace('.','')}
  function eventHtml(e){return `<button class="tlEvent ${typeClass(e.type)}" type="button" data-target="${safe(e.target||'timeline')}"><span class="tlDot"></span><div class="tlEventMain"><div class="tlEventTop"><b>${safe(e.title)}</b><span>${safe(e.type)}</span></div><p>${safe(e.sub||'registro preservado')}</p><small>${e.source?`Fonte: ${safe(e.source)}`:'Fonte não registrada'}${e.confidence?` · ${safe(confidence(e.confidence))}`:''}</small></div><i>›</i></button>`}
  function render(){const root=q('productTimeline');if(!root)return;const all=build(),sources=sourceOptions(all),term=norm(TL.query),filtered=all.filter(e=>inDays(e.date,TL.days)&&(TL.type==='all'||e.kind===TL.type)&&(TL.source==='all'||e.source===TL.source)&&(!term||norm(`${e.type} ${e.title} ${e.sub} ${e.source}`).includes(term))),shown=filtered.slice(0,TL.limit),dates=unique(filtered.map(e=>e.date)),domains=unique(filtered.map(e=>e.type)),latest=filtered[0]?.date||null,oldest=filtered.at(-1)?.date||null;
    const groups=[];let currentMonth=null,currentDay=null;for(const e of shown){const m=e.date.slice(0,7);if(m!==currentMonth){groups.push(`<div class="tlMonth"><span>${safe(monthLabel(e.date))}</span><i></i></div>`);currentMonth=m;currentDay=null}if(e.date!==currentDay){groups.push(`<div class="tlDay"><time>${safe(dayLabel(e.date))}</time></div>`);currentDay=e.date}groups.push(eventHtml(e))}
    root.innerHTML=`<div class="tlTitle"><div><div class="tlKicker">LINHA DO TEMPO LONGITUDINAL</div><h1>Timeline</h1><p>Uma única cronologia de treino, composição, exames, nutrição, atividade, documentos e qualidade de dados. Ausência de evento significa ausência de registro, não valor zero.</p></div><button class="productBtn" id="tlRefresh">Atualizar dados</button></div>
    ${TL.error?`<div class="tlWarning">O carregamento ampliado da timeline não terminou: ${safe(TL.error)}. A visão continua usando os dados já carregados pelo app.</div>`:''}
    <div class="tlControls"><select id="tlDays"><option value="30" ${TL.days==='30'?'selected':''}>30 dias</option><option value="90" ${TL.days==='90'?'selected':''}>90 dias</option><option value="365" ${TL.days==='365'?'selected':''}>1 ano</option><option value="all" ${TL.days==='all'?'selected':''}>Todo histórico</option></select><select id="tlType"><option value="all">Todos os domínios</option><option value="training" ${TL.type==='training'?'selected':''}>Treino</option><option value="body" ${TL.type==='body'?'selected':''}>Composição</option><option value="labs" ${TL.type==='labs'?'selected':''}>Exames</option><option value="nutrition" ${TL.type==='nutrition'?'selected':''}>Nutrição</option><option value="metrics" ${TL.type==='metrics'?'selected':''}>Atividade & sono</option><option value="activity" ${TL.type==='activity'?'selected':''}>Atividade importada</option><option value="document" ${TL.type==='document'?'selected':''}>Documentos</option><option value="quality" ${TL.type==='quality'?'selected':''}>Qualidade</option></select><select id="tlSource"><option value="all">Todas as fontes</option>${sources.map(s=>`<option value="${safe(s)}" ${TL.source===s?'selected':''}>${safe(s)}</option>`).join('')}</select><input id="tlQuery" type="search" value="${safe(TL.query)}" placeholder="Buscar evento, fonte ou contexto"></div>
    <div class="tlMetrics"><div><span>Eventos</span><strong>${filtered.length}</strong><small>${shown.length<filtered.length?shown.length+' exibidos':''}</small></div><div><span>Dias com evidência</span><strong>${dates.length}</strong><small>${latest?fmtDate(latest):'—'} → ${oldest?fmtDate(oldest):'—'}</small></div><div><span>Domínios</span><strong>${domains.length}</strong><small>${domains.slice(0,4).map(safe).join(' · ')}</small></div><div><span>Cobertura ampliada</span><strong>${TL.loaded?'ativa':'carregando'}</strong><small>${TL.loaded?'nutrição, métricas e atividade paginadas':'usando base inicial'}</small></div></div>
    <div class="tlLegend"><span><i class="train"></i>Treino</span><span><i class="body"></i>Composição</span><span><i class="nut"></i>Nutrição</span><span><i class="lab"></i>Exames</span><span><i class="activity"></i>Atividade/sono</span><span><i class="doc"></i>Documentos</span><span><i class="quality"></i>Qualidade</span></div>
    <div class="tlStream">${groups.join('')||'<div class="tlEmpty">Nenhum evento corresponde aos filtros.</div>'}</div>${shown.length<filtered.length?`<button class="tlMore" id="tlMore">Mostrar mais ${Math.min(36,filtered.length-shown.length)} eventos</button>`:''}<div class="tlFoot">A Timeline organiza registros observados e preserva a proveniência. Ela não reconstrói automaticamente dias sem dados e não converte associação temporal em causalidade.</div>`;
    q('tlDays').onchange=e=>{TL.days=e.target.value;TL.limit=36;render()};q('tlType').onchange=e=>{TL.type=e.target.value;TL.limit=36;render()};q('tlSource').onchange=e=>{TL.source=e.target.value;TL.limit=36;render()};q('tlQuery').oninput=e=>{TL.query=e.target.value;TL.limit=36;render()};q('tlMore')?.addEventListener('click',()=>{TL.limit+=36;render()});q('tlRefresh').onclick=async()=>{TL.loaded=false;TL.error=null;await load()};root.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{const t=b.dataset.target;if(t&&t!=='timeline')activateTab(t)});
  }
  const prior=loadAll;loadAll=async function(){const out=await prior();render();if(!TL.loaded&&!TL.loading)load();return out};
  sb.auth.getSession().then(({data})=>{if(data?.session)setTimeout(()=>{render();load()},2300)});
})();
