(function(){
  'use strict';
  const day=v=>String(v||'').slice(0,10);
  const num=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
  const safe=v=>esc(v??'');
  const unique=a=>[...new Set(a.filter(Boolean))];
  const age=v=>{if(!v)return null;const t=Date.parse(day(v)+'T12:00:00');if(!Number.isFinite(t))return null;return Math.max(0,Math.floor((Date.now()-t)/86400000))};
  const ageText=v=>{const a=age(v);return a==null?'sem dado':a===0?'hoje':a===1?'há 1 dia':`há ${a} dias`};
  const cutoff=n=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-n+1);return d.toISOString().slice(0,10)};
  function latest(arr,key){return [...(arr||[])].filter(x=>x?.[key]).sort((a,b)=>String(b[key]).localeCompare(String(a[key])))[0]||null}
  function exFor(w){if(!w)return[];const all=state.exercises||[],direct=all.filter(e=>e.workout_source_record_id&&e.workout_source_record_id===w.source_record_id);return (direct.length?direct:all.filter(e=>day(e.workout_date)===day(w.workout_date))).sort((a,b)=>(a.order_index??999)-(b.order_index??999))}
  function setsFor(e){return (state.sets||[]).filter(s=>s.exercise_source_record_id===e.source_record_id)}
  function freshness(label,date,detail,status){return`<div class="tdFresh"><i class="${status||''}"></i><div><b>${safe(label)}</b><small>${safe(detail||'sem detalhe')}</small></div><time>${ageText(date)}</time></div>`}
  function workoutEvidence(w){if(!w)return'';const bits=[];if(num(w.duration_minutes)!=null)bits.push(`${fmtNum(w.duration_minutes,0)} min`);if(num(w.calories_kcal)!=null)bits.push(`${fmtNum(w.calories_kcal,0)} kcal`);if(num(w.heart_rate_avg)!=null)bits.push(`FC média ${fmtNum(w.heart_rate_avg,0)} bpm`);if(num(w.heart_rate_max)!=null)bits.push(`máx. ${fmtNum(w.heart_rate_max,0)} bpm`);return bits.join(' · ')}
  function eventRows(){const rows=[];(state.canonicalWorkouts||[]).forEach(w=>rows.push({d:w.workout_date,t:'Treino',a:w.workout_type||'Treino',b:w.location||''}));(state.body||[]).forEach(x=>rows.push({d:x.measured_at,t:'Composição',a:'Medição corporal',b:x.source||''}));const labs={};for(const x of state.labs||[]){const d=day(x.collection_date);labs[d]=(labs[d]||0)+1}Object.entries(labs).forEach(([d,n])=>rows.push({d,t:'Exames',a:`Coleta laboratorial`,b:`${n} resultado(s) estruturado(s)`}));return rows.sort((a,b)=>String(b.d).localeCompare(String(a.d))).slice(0,8)}
  function render(){
    const root=q('productToday');if(!root)return;const workouts=[...(state.canonicalWorkouts||[])].sort((a,b)=>String(b.workout_date).localeCompare(String(a.workout_date))),lastW=workouts[0],ex=exFor(lastW),setCount=ex.reduce((n,e)=>n+setsFor(e).length,0),body=latest(state.body,'measured_at'),prevBody=[...(state.body||[])].sort((a,b)=>String(b.measured_at).localeCompare(String(a.measured_at)))[1],labs=latest(state.labs,'collection_date'),nut=latest(state.nutrition,'nutrition_date'),sleep=latest((state.metrics||[]).filter(x=>x.metric_type==='sleep_duration_h'),'measured_at'),openQuality=(state.quality||[]).filter(x=>String(x.status).toLowerCase()==='open'),c14=cutoff(14),c28=cutoff(28),w14=workouts.filter(x=>day(x.workout_date)>=c14).length,wPrev=workouts.filter(x=>day(x.workout_date)>=c28&&day(x.workout_date)<c14).length,nut14=unique((state.nutrition||[]).filter(x=>day(x.nutrition_date)>=c14).map(x=>day(x.nutrition_date))).length,events=eventRows(),partial=lastW?.record_status==='review_required',evidence=workoutEvidence(lastW);
    const bodyDelta=body&&prevBody&&num(body.weight_kg)!=null&&num(prevBody.weight_kg)!=null?num(body.weight_kg)-num(prevBody.weight_kg):null;
    root.innerHTML=`<div class="tdHero"><div class="tdHeroMain"><div class="tdKicker">LTS HEALTH · HOJE</div><h1>Seu histórico atual, sem ruído.</h1><p>O painel prioriza o que mudou, o que foi registrado recentemente e onde ainda existe uma lacuna explícita.</p><div class="tdHeroGrid"><div><span>Último treino</span><strong>${lastW?fmtDate(lastW.workout_date):'—'}</strong><small>${safe(lastW?.workout_type||'sem sessão')}</small></div><div><span>Última composição</span><strong>${body?fmtDate(body.measured_at):'—'}</strong><small>${body?.weight_kg!=null?fmtNum(body.weight_kg,1)+' kg registrados':'sem peso estruturado'}</small></div><div><span>Última nutrição</span><strong>${nut?fmtDate(nut.nutrition_date):'—'}</strong><small>${nut?'MyFitnessPal / fonte registrada':'sem registro recente'}</small></div><div><span>Qualidade aberta</span><strong>${openQuality.length}</strong><small>lacunas preservadas</small></div></div></div><div class="tdQuick"><b>Ações rápidas</b><div><button id="tdGoTraining" class="productBtn primary">Ver treino</button><button id="tdAddBody" class="productBtn">Bioimpedância</button><button id="tdGoInbox" class="productBtn">Adicionar dados</button></div></div></div>
      <div class="tdGrid"><section class="tdPanel latest"><div class="tdPanelHead"><div><b>Último treino registrado</b><small>Exercícios e séries vêm do registro estruturado; campos ausentes permanecem ausentes.</small></div><span class="tdState ${partial?'review':'ok'}">${partial?'registro parcial':'validado'}</span></div>${lastW?`<div class="tdWorkoutHead"><div><strong>${fmtDate(lastW.workout_date)} · ${safe(lastW.workout_type||'Treino')}</strong><small>${safe(lastW.location||'local não informado')} · ${ex.length} exercício(s) · ${setCount} série(s) estruturada(s)</small>${evidence?`<small>${safe(evidence)} · fonte preservada</small>`:''}</div><button id="tdOpenTraining">Abrir histórico</button></div>${partial?`<div class="tdWarning"><b>Há informação faltante nesta sessão.</b><span>${safe(lastW.notes||'O registro está marcado para revisão; nenhum campo faltante foi inferido.')}</span></div>`:''}<div class="tdExercisePreview">${ex.slice(0,7).map(e=>{const ss=setsFor(e);return`<div><b>${safe(e.exercise||'Exercício')}</b><small>${[e.machine,e.muscle_group].filter(Boolean).map(safe).join(' · ')||'sem detalhe'} · ${ss.length?ss.length+' série(s)':'detalhe parcial'}</small></div>`}).join('')||'<div class="tdEmpty">Sessão preservada sem exercícios estruturados.</div>'}${ex.length>7?`<div class="tdMore">+ ${ex.length-7} exercício(s) no histórico</div>`:''}</div>`:'<div class="tdEmpty">Sem treino registrado.</div>'}</section>
      <section class="tdPanel"><div class="tdPanelHead"><div><b>Frescor das fontes</b><small>Quando a fonte está antiga ou ausente, o painel mostra isso em vez de preencher a lacuna.</small></div></div><div class="tdFreshList">${freshness('Treino',lastW?.workout_date,lastW?.workout_type,partial?'review':'ok')}${freshness('Composição',body?.measured_at,body?.source,'ok')}${freshness('Nutrição',nut?.nutrition_date,nut?.source||'MyFitnessPal',nut?'ok':'')}${freshness('Sono',sleep?.measured_at,sleep?.source||'Apple Health não consolidado',sleep?'ok':'')}${freshness('Laboratório',labs?.collection_date,labs?.laboratory||'coleta estruturada',labs?'ok':'')}</div></section></div>
      <div class="tdMetrics"><div><span>Treinos · 14 dias</span><strong>${w14}</strong><small>janela anterior: ${wPrev}</small></div><div><span>Nutrição registrada · 14 dias</span><strong>${nut14}/14</strong><small>dias com evidência, não aderência</small></div><div><span>Diferença entre 2 últimas pesagens</span><strong>${bodyDelta==null?'—':`${bodyDelta>0?'+':''}${fmtNum(bodyDelta,1)} kg`}</strong><small>descrição do registro, sem julgamento corporal</small></div><div><span>Última coleta laboratorial</span><strong>${labs?fmtDate(labs.collection_date):'—'}</strong><small>${labs?'resultado estruturado disponível':'sem coleta estruturada'}</small></div></div>
      <div class="tdGrid lower"><section class="tdPanel"><div class="tdPanelHead"><div><b>Atividade recente</b><small>Eventos canônicos mais recentes.</small></div></div><div class="tdEvents">${events.map(x=>`<div><time>${fmtDate(x.d)}</time><span>${safe(x.t)}</span><div><b>${safe(x.a)}</b><small>${safe(x.b)}</small></div></div>`).join('')||'<div class="tdEmpty">Sem eventos recentes.</div>'}</div></section><section class="tdPanel"><div class="tdPanelHead"><div><b>Pendências de evidência</b><small>Questões abertas permanecem visíveis até existir informação suficiente para resolvê-las.</small></div><span>${openQuality.length}</span></div><div class="tdIssues">${openQuality.slice(0,8).map(x=>`<div><b>${safe(x.entity_name||x.category||'Questão de dados')}</b><small>${safe(x.description||x.issue_code||'sem descrição')}</small><span>${safe(x.severity||'')}</span></div>`).join('')||'<div class="tdEmpty">Nenhuma questão aberta no ledger.</div>'}</div></section></div>`;
    q('tdGoTraining').onclick=()=>activateTab('training');q('tdOpenTraining')?.addEventListener('click',()=>activateTab('training'));q('tdAddBody').onclick=()=>q('v14AddBody')?.click();q('tdGoInbox').onclick=()=>activateTab('inbox');
  }
  const prior=loadAll;loadAll=async function(){const out=await prior();render();return out};
  sb.auth.getSession().then(({data})=>{if(data?.session)setTimeout(render,2150)});
})();
