import {state,routes,signIn,signOut,restoreSession,subscribeAuth,uploadFile,setGlobalPeriod} from './core.js';
import {loadInitialData,ensureRouteData,isRouteReady,refreshData,downloadStructuredBackup} from './data-layer.js';
import {renderBioHub} from './bio-screen.js';
import {renderTrainingScreen} from './training-screen.js';
import {renderEvolutionHub} from './evolution-screen.js';
import {renderAnalysisHub} from './analysis-screen.js';
import {renderTreatmentHub} from './treatment-screen.js';
import {renderHealthHub} from './health-screen.js';
import {renderNutritionHub} from './nutrition-screen.js';
import {renderTodayHub} from './today-screen.js';
import {renderDataHub} from './data-screen.js';
import {renderTimelineHub} from './timeline-screen.js';
import {renderProductHome,renderProductTraining} from './product-layout-v2.js';
import {mountEvidencePanels} from './evidence-priority.js';
import {openEntry,setupEntryController} from './entry.js';

const $=id=>document.getElementById(id);
const fixtureMode=new URLSearchParams(location.search).has('fixture');
const screenRenderers={bio:renderBioHub,treinos:fixtureMode?renderTrainingScreen:renderProductTraining,evolucao:renderEvolutionHub,analise:renderAnalysisHub,tratamentos:renderTreatmentHub,saude:renderHealthHub,nutricao:renderNutritionHub,hoje:fixtureMode?renderTodayHub:renderProductHome,dados:renderDataHub,timeline:renderTimelineHub};
const mobileMoreRoutes=new Set(['bio','nutricao','saude','tratamentos','evolucao','dados']);
let authSubscription=null,renderQueued=false,loginBusy=false,renderedRoute=null;

function setSync(text){const a=$('syncText'),b=$('railSyncText');if(a)a.textContent=text;if(b)b.textContent=text;}
function showLogin(message=''){$('login')?.classList.remove('hidden');$('app')?.classList.add('hidden');$('moreSheet')?.classList.add('hidden');$('entryModal')?.classList.add('hidden');if($('loginMsg'))$('loginMsg').textContent=message;}
function showApp(){$('login')?.classList.add('hidden');$('app')?.classList.remove('hidden');}
function syncNav(){
  document.querySelectorAll('#primaryNav [data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route||(b.dataset.route==='mais'&&state.route==='evolucao')));
  document.querySelectorAll('#moreSheet [data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));
  document.querySelectorAll('#mobileNav [data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route||(b.dataset.route==='mais'&&mobileMoreRoutes.has(state.route))));
  const action=$('routeAction');if(!action)return;
  if(state.route==='bio'){action.textContent='Registrar bio';action.dataset.entry='body';action.classList.remove('hidden');}
  else if(state.route==='treinos'){action.textContent='Registrar treino';action.dataset.entry='workout';action.classList.remove('hidden');}
  else if(state.route==='nutricao'||state.route==='hoje'){action.textContent='Importar água do MFP';action.dataset.entry='water-import';action.classList.remove('hidden');}
  else{action.classList.add('hidden');action.dataset.entry='';}
}
function resetScroll(){window.scrollTo({top:0,left:0,behavior:'auto'});const h=$('screenHost');h?.scrollTo({top:0,left:0,behavior:'auto'});}
function setRoute(route,{replace=true}={}){if(route==='mais'){$('moreSheet')?.classList.remove('hidden');return;}if(!routes.has(route))route='hoje';state.route=route;$('moreSheet')?.classList.add('hidden');try{localStorage.setItem('lts-health-v2-route',route);}catch{}const u=`#${route}`;replace?history.replaceState(null,'',u):history.pushState(null,'',u);syncNav();scheduleRender();if(state.loaded)ensureRouteData(route,setSync).then(scheduleRender);resetScroll();}
function routeFromLocation(){const hash=location.hash.replace(/^#/,'');if(routes.has(hash))return hash;try{const saved=localStorage.getItem('lts-health-v2-route');if(routes.has(saved))return saved;}catch{}return'hoje';}
function loadingView(text='Carregando seus dados'){return`<div class="loadingState"><div class="spinner"></div><b>${text}</b><span>Preparando esta área.</span></div>`;}
function applyControlState(){const v={trainingPeriod:state.ui.trainingPeriod,analysisPeriod:state.ui.analysisPeriod,timelinePeriod:state.ui.timelinePeriod,timelineYear:state.ui.timelineYear,timelineDomain:state.ui.timelineDomain,nutritionPeriod:state.ui.nutritionPeriod,nutritionYear:state.ui.nutritionYear,compareA:state.ui.compareA,compareB:state.ui.compareB,segmentalCompareDate:state.ui.segmentalCompareDate,collectionSelect:state.ui.selectedCollection,dataUploadStatus:state.ui.dataUploadStatus,dataUploadSource:state.ui.dataUploadSource};for(const[id,value]of Object.entries(v)){const el=$(id);if(el&&value!=null)el.value=value;}}
function render(){renderQueued=false;if(!$('app')||$('app').classList.contains('hidden'))return;const host=$('screenHost');if(!state.loaded){host.innerHTML=loadingView();syncNav();return;}if(!isRouteReady(state.route)){host.innerHTML=loadingView('Carregando esta área');syncNav();return;}const renderer=screenRenderers[state.route]||screenRenderers.hoje;try{host.innerHTML=renderer();}catch(error){console.error(error);host.innerHTML='<div class="errorState"><b>Não foi possível abrir esta área.</b><span>Os outros dados continuam disponíveis.</span></div>';}applyControlState();mountEvidencePanels();if(renderedRoute!==state.route)resetScroll();renderedRoute=state.route;syncNav();}
function scheduleRender(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(render);}
async function refresh(){if(state.loading)return;setSync('Atualizando…');scheduleRender();await refreshData(state.route,setSync);scheduleRender();}

export function uploadOutcomeMessage(result){if(result?.processing==='review_required')return'Arquivo recebido e preservado. A leitura automática não terminou; ficou aguardando leitura segura.';if(result?.processing==='status_unknown')return'Arquivo recebido e preservado. Não foi possível atualizar o resultado da leitura agora; confira em Arquivos & fontes antes de reenviar.';return'Arquivo recebido. A leitura foi iniciada.';}
export function uploadOutcomeMessageFromState(result){const id=String(result?.id||'');if(!id)return uploadOutcomeMessage(result);const upload=(state.data.uploads||[]).find(r=>String(r.id)===id);const preview=(state.data.previews||[]).find(r=>String(r.upload_id)===id);const status=String(upload?.status||'').toLowerCase(),source=String(upload?.source_type||'').toLowerCase();if(status==='imported'){if(source==='apple_health')return'Arquivo incorporado ao histórico. Dados com regra segura entraram; sono e outras métricas sem regra segura continuam separados aguardando conferência.';return'Arquivo incorporado ao histórico.';}if(status==='review_required'){const format=preview?.detected_format?` (${String(preview.detected_format).toUpperCase()})`:'';return`Arquivo recebido e guardado${format}. Ainda não entrou nas análises e você não precisa revisar linha por linha.`;}if(status==='processed')return'Arquivo processado e guardado. O histórico de arquivos já registra a conclusão.';if(status==='rejected'||status==='failed')return'O arquivo foi guardado, mas não foi possível concluir o processamento. Para tentar novamente, envie outra versão do arquivo.';if(status==='uploaded'||status==='processing')return'Arquivo recebido e guardado. A leitura ainda está em andamento.';return uploadOutcomeMessage(result);}
async function doLogin(){if(loginBusy)return;const button=$('loginBtn'),email=$('email')?.value.trim(),password=$('password')?.value;loginBusy=true;if(button){button.disabled=true;button.setAttribute('aria-busy','true');}if($('loginMsg'))$('loginMsg').textContent='Entrando…';try{await signIn(email,password);if($('loginMsg'))$('loginMsg').textContent='';showApp();setRoute(routeFromLocation());await loadInitialData(setSync);await ensureRouteData(state.route,setSync);scheduleRender();}catch(error){console.error(error);if($('loginMsg'))$('loginMsg').textContent='Não foi possível entrar. Confira e tente novamente.';}finally{loginBusy=false;if(button){button.disabled=false;button.removeAttribute('aria-busy');}}}
function openTimelineTarget(b){const route=b.dataset.timelineRoute,kind=b.dataset.timelineKind,ref=b.dataset.timelineRef||'',date=b.dataset.timelineDate||'';if(kind==='workout'){setGlobalPeriod('all');state.ui.openWorkout=ref;}else if(kind==='body')state.ui.selectedBodyDate=ref||date;else if(kind==='nutrition'){setGlobalPeriod('all');state.ui.nutritionYear=String(date).slice(0,4);state.ui.nutritionDate=date;}else if(kind==='labs'){state.ui.selectedCollection=ref;state.ui.labQuery='';}if(route)setRoute(route,{replace:false});}
function bindStaticEvents(){
  document.addEventListener('click',async e=>{
    const backup=e.target.closest('#backupExportBtn');if(backup){const msg=$('backupExportMsg');backup.disabled=true;if(msg)msg.textContent='Preparando backup…';try{const r=await downloadStructuredBackup(t=>{if(msg)msg.textContent=t;setSync(t);});if(msg)msg.textContent=`Backup criado: ${r.filename}`;}catch(err){console.error(err);if(msg)msg.textContent='Não foi possível criar o backup agora.';}finally{backup.disabled=false;}return;}
    const source=e.target.closest('[data-source-upload]');if(source){if($('uploadType'))$('uploadType').value=source.dataset.sourceUpload;$('uploadFile')?.focus();return;}
    const more=e.target.closest('[data-timeline-more]');if(more){state.ui.timelineLimit=Number(state.ui.timelineLimit||250)+250;scheduleRender();return;}
    const jump=e.target.closest('[data-timeline-jump]');if(jump){openTimelineTarget(jump);return;}
    const entry=e.target.closest('[data-entry]');if(entry?.dataset.entry){openEntry(entry.dataset.entry);return;}
    const evidence=e.target.closest('[data-evidence-route]');if(evidence){e.preventDefault();setRoute(evidence.dataset.evidenceRoute,{replace:false});return;}
    const period=e.target.closest('button[data-period]');if(period){e.preventDefault();setGlobalPeriod(period.dataset.period);scheduleRender();return;}
    const route=e.target.closest('[data-route]');if(route){e.preventDefault();setRoute(route.dataset.route,{replace:false});return;}
    const workout=e.target.closest('[data-workout]');if(workout){state.ui.openWorkout=workout.dataset.workout;scheduleRender();return;}
    const map=[['data-home-metric','homeMetric'],['data-bio-metric','bioMetric'],['data-body-date','selectedBodyDate'],['data-evolution-metric','evolutionMetric'],['data-segmental-date','segmentalDate'],['data-nutrition-date','nutritionDate'],['data-exercise','selectedExercise'],['data-marker','selectedBiomarker']];for(const[attr,key]of map){const b=e.target.closest(`[${attr}]`);if(b){state.ui[key]=b.getAttribute(attr);scheduleRender();return;}}
  });
  document.addEventListener('input',e=>{const map={trainingQuery:'trainingQuery',exerciseQuery:'exerciseQuery',timelineQuery:'timelineQuery',labQuery:'labQuery',treatmentQuery:'treatmentQuery'};const key=map[e.target.id];if(key){state.ui[key]=e.target.value;if(key==='timelineQuery')state.ui.timelineLimit=250;scheduleRender();}});
  document.addEventListener('change',e=>{if(['trainingPeriod','analysisPeriod'].includes(e.target.id)){setGlobalPeriod(e.target.value);scheduleRender();return;}const map={timelinePeriod:'timelinePeriod',timelineYear:'timelineYear',timelineDomain:'timelineDomain',nutritionPeriod:'nutritionPeriod',nutritionYear:'nutritionYear',compareA:'compareA',compareB:'compareB',segmentalCompareDate:'segmentalCompareDate',collectionSelect:'selectedCollection',dataUploadStatus:'dataUploadStatus',dataUploadSource:'dataUploadSource'};const key=map[e.target.id];if(key){state.ui[key]=e.target.value;scheduleRender();}});
  document.addEventListener('submit',async e=>{if(e.target.id!=='uploadForm')return;e.preventDefault();const file=$('uploadFile')?.files?.[0],type=$('uploadType')?.value||'other',msg=$('uploadMsg'),button=e.target.querySelector('button[type="submit"]');if(msg)msg.textContent='Enviando…';if(button)button.disabled=true;let result;try{result=await uploadFile(file,type);if(msg)msg.textContent=uploadOutcomeMessage(result);await refresh();if(msg)msg.textContent=uploadOutcomeMessageFromState(result);}catch(err){console.error(err);if(msg)msg.textContent='Não foi possível enviar este arquivo agora.';}finally{if(button)button.disabled=false;}});
  $('loginBtn')?.addEventListener('click',doLogin);$('password')?.addEventListener('keydown',e=>{if(e.key==='Enter')doLogin();});$('refreshBtn')?.addEventListener('click',refresh);$('logoutBtn')?.addEventListener('click',async()=>{await signOut();state.loaded=false;state.data={};state.domainStatus={};showLogin();});$('closeMore')?.addEventListener('click',()=>$('moreSheet')?.classList.add('hidden'));$('moreSheet')?.addEventListener('click',e=>{if(e.target===$('moreSheet'))$('moreSheet').classList.add('hidden');});window.addEventListener('popstate',()=>setRoute(routeFromLocation()));window.addEventListener('hashchange',()=>{const r=routeFromLocation();if(r!==state.route)setRoute(r);});window.addEventListener('online',()=>setSync(state.loaded?'Online':'Conectado'));window.addEventListener('offline',()=>setSync('Sem conexão'));
}
async function boot(){bindStaticEvents();setupEntryController({onSaved:refresh});state.route=routeFromLocation();try{const session=await restoreSession();if(!session)showLogin();else{showApp();setRoute(state.route);await loadInitialData(setSync);await ensureRouteData(state.route,setSync);scheduleRender();}}catch(error){console.error(error);showLogin('Não foi possível restaurar sua sessão.');}authSubscription=subscribeAuth(session=>{state.session=session;if(!session){state.loaded=false;state.data={};state.domainStatus={};showLogin();}});}
window.addEventListener('beforeunload',()=>authSubscription?.unsubscribe?.());
boot();
