import {state,esc,fmtNum,fmtDate,num,day,norm} from './core.js';
import {homeCockpitModel,nutritionPanel,waterPanel} from './home-cockpit.js';
import {renderGoals,goalForDate} from './personal-goals.js';

const v=(n,unit)=>num(n)==null?'Não informado':`${fmtNum(n,0)} ${unit}`;
export function renderProductNutrition(){
  const period=state.ui.nutritionPeriod||state.ui.analysisPeriod||'90';
  const c=homeCockpitModel(state.data,state.domainStatus,period,state.ui),n=c.r.nutrition;
  const date=n.rows.some(r=>r.date===state.ui.nutritionDate)?state.ui.nutritionDate:n.rows.at(-1)?.date;
  const food=n.rows.find(r=>r.date===date),goal=goalForDate(c.goals,date);
  const meals=state.domainStatus.meals==='ready'?(state.data.meals||[]).filter(r=>day(r.meal_date)===date&&norm(r.source)===n.source?.key):[];
  const fields=[['calories_kcal','Energia','kcal'],['protein_g','Proteína','g'],['carbs_g','Carboidratos','g'],['fat_g','Gorduras','g'],['fiber_g','Fibra','g']];
  const diary=food?`<label class="ltsEvolutionSource">Dia do diário<select id="nutritionDateProduct">${[...n.rows].reverse().map(r=>`<option value="${r.date}" ${r.date===date?'selected':''}>${fmtDate(r.date)}${r.date===c.m.today?' · em andamento':''}</option>`).join('')}</select></label><div class="ltsNutritionDiaryMetrics">${fields.map(([key,label,unit])=>`<article><span>${label}</span><b>${v(food[key],unit)}</b><small>${num(goal?.[key])>0?`Meta vigente: ${v(goal[key],unit)}`:'Sem meta neste dia'}</small></article>`).join('')}</div>${date===c.m.today?'<p>Diário em andamento; fica fora das médias e comparações.</p>':''}<h3>Refeições desse dia</h3>${meals.length?`<div class="ltsNutritionMeals">${meals.map(r=>`<article><b>${esc(r.meal_name||'Refeição')}</b><p>${v(r.calories_kcal,'kcal')} · ${v(r.protein_g,'g proteína')} · ${v(r.carbs_g,'g carboidratos')} · ${v(r.fat_g,'g gorduras')}</p>${r.notes?`<p>${esc(r.notes)}</p>`:''}</article>`).join('')}</div>`:`<p>${state.domainStatus.meals==='error'?'Refeições indisponíveis nesta atualização.':'Esta origem ainda não forneceu o detalhamento das refeições. Os totais diários acima continuam disponíveis.'}</p>`}`:'<p>Sem diário inequívoco nesta origem e janela. Amplie o período ou selecione outra origem.</p>';
  const comparisons=c.evo.insights.nutrition.rows.filter(r=>r.comparable);
  const contrast=comparisons.length?`<section class="ltsCockpitPanel"><header><h2>Alimentação e dias de treino</h2></header><div class="ltsNutritionDiaryMetrics">${comparisons.map(r=>`<article><span>${esc(r.label)}</span><b>${v(r.withMean,r.unit)}</b><small>Nos dias com treino registrado</small><b>${v(r.withoutMean,r.unit)}</b><small>Nos dias sem treino registrado</small></article>`).join('')}</div><p>Mesma origem alimentar; ${esc(n.source?.label||'')}. Comparações de dias encerrados, com ao menos 5 valores por grupo. Descrevem o registro; não provam efeito do treino nem adequação do plano.</p></section>`:'';
  return `<section class="ltsHomeV2 ltsHomeReference ltsEvolutionHome ltsNutritionProduct"><div class="ltsCockpitWindow"><span>Janela de análise</span><div class="ltsHomePeriod" role="group" aria-label="Janela de análise">${[['30','30 dias'],['90','90 dias'],['365','1 ano'],['all','Histórico']].map(([key,label])=>`<button data-period="${key}" aria-pressed="${period===key}">${label}</button>`).join('')}</div></div><header class="ltsCockpitHeading"><div><span class="ltsEvolutionEyebrow">ALIMENTAÇÃO E HIDRATAÇÃO</span><h1>Seu consumo.<br>O contexto do seu plano.</h1><p>Totais, refeições e metas na origem e na data corretas.</p></div></header><div class="ltsCockpitGrid nutrition">${nutritionPanel(c)}${waterPanel(c)}</div><section class="ltsCockpitPanel ltsNutritionDiary"><header><h2>Investigar o diário</h2></header>${diary}</section>${contrast}${renderGoals()}<details class="ltsEvolutionDiagnostics"><summary>Limites e origem dos registros</summary><p>Fonte alimentar: ${esc(n.source?.label||'sem origem na janela')}. Último diário: ${food?fmtDate(n.rows.at(-1).date):'nenhum'}. Dias ausentes não representam consumo zero. Totais ambíguos ficam fora das comparações.</p><p>A água mostra os registros recebidos pela integração, com sua data. A chegada de um arquivo não confirma a recorrência automática.</p><button data-route="dados">Conferir integrações ↗</button></details></section>`;
}
