import {state,esc,fmtDate,fmtNum,num,norm} from './core.js';
import {usefulReports,segments} from './reports-model.js';
import {contextChart,bodySourceLabel} from './health-context.js';
import {labResultText} from './labs-layout-v2.js';
import {pageOf,pager} from './history-tools.js';
import {screenTitle} from './product-shell.js';

const value=(v,unit='',digits=1)=>num(v)==null?'Sem dado':`${fmtNum(v,digits)}${unit?` ${unit}`:''}`;
const delta=(v,unit='',digits=1)=>num(v)==null?'Sem comparação':`${v>0?'+':''}${value(v,unit,digits)}`;
const range=b=>`${b.start?fmtDate(b.start):'Início do histórico'} → ${fmtDate(b.end)}`;
const note=text=>`<p class="ltsReportNote">${esc(text)}</p>`;
const empty=text=>`<div class="ltsReportEmpty" role="status">${esc(text)}</div>`;
const options=(rows,selected,all=false)=>`${all?'<option value="all">Todas as origens</option>':''}${rows.map(([k,label])=>`<option value="${esc(k)}" ${k===selected?'selected':''}>${esc(label)}</option>`).join('')}`;
const select=(id,label,rows,selected,all=false)=>`<label class="ltsField">${esc(label)}<select id="${id}" data-report-field="${id}">${options(rows,selected,all)}</select></label>`;
const reason=key=>({source_changed:'As medições mais recentes têm origens ou aparelhos diferentes. Os valores aparecem no histórico, mas a diferença automática fica bloqueada.',ambiguous:'Há mais de uma medição na data. Consulte os registros individuais; nenhuma foi escolhida automaticamente.',single:'Há apenas uma medição nesta origem e janela. Uma segunda medição compatível permitirá comparar.',empty:'Não há medição nesta janela.',unavailable:'Esta área não carregou. Use Atualizar para tentar novamente.',unavailable_context:'A origem corporal não carregou; a comparação segmentar fica bloqueada até essa conferência.'}[key]||'Não há base comparável nesta janela.');
const metricDefs=[['weight_kg','Peso','kg',1],['skeletal_muscle_mass_kg','Massa muscular esquelética','kg',1],['fat_mass_kg','Massa de gordura','kg',1],['body_fat_pct','Gordura corporal','%',1]];
const signalLabels={sleep_duration_h:'Duração do sono',resting_heart_rate_bpm:'Frequência cardíaca em repouso',hrv_sdnn_ms:'Variabilidade cardíaca (SDNN)',steps:'Passos'};

function finding(title,observation,investigation,route,evidence){
  return `<article class="ltsReportFinding"><h3>${esc(title)}</h3><p>${esc(observation)}</p><details><summary>O que investigar</summary><p>${esc(investigation)}</p><small>${esc(evidence)}</small></details><button type="button" data-route="${route}">Abrir evidências ›</button></article>`;
}
function findings(m){
  const cards=[],s=m.segmental,part=s.parts.find(p=>p.key===s.region);
  if(s.available&&part?.delta!=null){
    const training=s.training,previous=s.previousTraining,n=s.nutrition;
    cards.push(finding(`${part.label}: ${part.delta<0?'redução':part.delta>0?'aumento':'estabilidade'} de massa magra registrada`,`${delta(part.delta,'kg',2)} entre ${fmtDate(s.start)} e ${fmtDate(s.end)}. No mesmo intervalo: ${training?.sessions==null?'treino regional indisponível':`${training.sessions} sessões com grupos dessa região`} e ${n?.counts?.protein_g?`${value(n.means.protein_g,'g',0)} de proteína por dia registrado (${n.counts.protein_g} dias)`:'alimentação sem cobertura para proteína'}.`,`A massa magra segmentar inclui água e outros tecidos; a variação não comprova perda de músculo. Compare condições da bioimpedância e discuta com o treinador a seleção de exercícios, as cargas e as séries registradas. ${previous?.sets!=null&&training?.sets!=null?`Séries no intervalo anterior de igual duração: ${previous.sets}; no intervalo entre medições: ${training.sets}. `:''}Esses grupos não representam todo estímulo indireto de exercícios compostos.`, 'bio',`${range(s.interval)} · origens registradas preservadas; modelo e condições de medição podem estar incompletos.`));
  }else if(s.rows.length){
    cards.push(finding('A evolução regional precisa de uma base compatível',reason(s.reason),'Confira as medições no gráfico segmentar. Uma alteração isolada, uma origem diferente ou condições de medição desconhecidas não justificam concluir que o treino está errado.','bio','Análise segmentar · datas e aparelho/origem disponíveis no relatório.'));
  }
  if(m.body.available){
    const b=m.body,c=b.changes;
    cards.push(finding('Peso, gordura e músculo no mesmo intervalo',`De ${fmtDate(b.start)} a ${fmtDate(b.end)}: peso ${delta(c.weight_kg,'kg')}, gordura ${delta(c.fat_mass_kg,'kg')} e músculo esquelético ${delta(c.skeletal_muscle_mass_kg,'kg')}.`,'Leia os três resultados juntos. Se houver queda de músculo registrada, confira repetição da medição, água corporal e cobertura de alimentação e treino antes de discutir ajustes com seus profissionais.','bio',`${bodySourceLabel(b.latest)} · diferença entre as duas últimas medições inequívocas dessa origem dentro da janela.`));
  }
  if(m.prior?.training.available&&m.training.available&&(m.prior.training.sessions||m.training.sessions)){
    cards.push(finding('Seu ritmo de treino tem uma comparação de períodos',`${m.prior.training.sessions} sessões registradas em ${range(m.previous)} e ${m.training.sessions} em ${range(m.current)}. ${m.training.sets==null?'As séries não estão disponíveis nesta atualização.':`${m.training.sets} séries registradas no período atual.`}`,'Abra sessões e progressão de carga no mesmo exercício, equipamento e local. Mais sessões ou séries, isoladamente, não demonstram melhor estímulo ou recuperação; ausência de registro não confirma ausência de treino.','treinos','Períodos de igual duração; somente sessões confirmadas.'));
  }
  const l=m.labs.comparisons.find(r=>r.comparable&&r.delta!==0);
  if(l)cards.push(finding(`${l.group.label}: mudança laboratorial comparável`,`${labResultText(l.previous)} em ${fmtDate(l.previous.collection_date)} → ${labResultText(l.current)} em ${fmtDate(l.current.collection_date)} (${delta(l.delta,l.current.unit,2)}).`,'Consulte a referência de cada coleta e leve o histórico ao médico. A direção da mudança não indica, sozinha, melhora ou piora e não determina ajuste de medicação.','saude',`${l.current.laboratory||l.current.source} · unidade e método registrados iguais.`));
  if(!m.nutrition.counts.protein_g&&m.nutrition.available)cards.push(finding('A alimentação recente limita os cruzamentos',`Não há proteína registrada em ${range(m.current)}.${m.lastNutrition?` Última alimentação disponível: ${fmtDate(m.lastNutrition)}.`:''}`,'A conexão alimentar precisa trazer dias recentes antes que o app relacione nutrição às mudanças corporais. O histórico anterior continua disponível em Nutrição.','nutricao','Sem estimativa de ingestão e sem transformar dias ausentes em zero.'));
  return `<section class="ltsReportSection"><h2>O que merece investigação</h2><div class="ltsReportFindings">${cards.length?cards.slice(0,4).join(''):empty('Ainda não há comparação sustentada nesta janela. Explore o histórico ou escolha uma janela maior.')}</div></section>`;
}
function periodComparison(m){
  const rows=[['Sessões registradas',m.training.sessions,m.prior?.training.sessions,'',0,null],['Séries registradas',m.training.sets,m.prior?.training.sets,'',0,null],['Tempo dos treinos',m.training.minutes,m.prior?.training.minutes,'min',0,null],['Proteína por dia registrado',m.nutrition.means.protein_g,m.prior?.nutrition.means.protein_g,'g',0,'protein_g'],['Calorias por dia registrado',m.nutrition.means.calories_kcal,m.prior?.nutrition.means.calories_kcal,'kcal',0,'calories_kcal']];
  return `<section class="ltsReportSection"><h2>Período atual × anterior</h2>${m.previous?`<div class="ltsReportTableWrap"><table class="ltsReportTable"><thead><tr><th scope="col">Medida</th><th scope="col">${esc(range(m.previous))}</th><th scope="col">${esc(range(m.current))}</th><th scope="col">Diferença</th></tr></thead><tbody>${rows.map(([label,current,prior,unit,digits,key])=>`<tr><th scope="row">${label}</th><td>${value(prior,unit,digits)}${key?`<small>${m.prior.nutrition.counts[key]??0} dias com valor</small>`:''}</td><td>${value(current,unit,digits)}${key?`<small>${m.nutrition.counts[key]??0} dias com valor</small>`:''}</td><td>${key&&!m.nutritionComparable?'Origem sem comparação':num(current)!=null&&num(prior)!=null?delta(current-prior,unit,digits):'Sem comparação'}</td></tr>`).join('')}</tbody></table></div>${note('As médias alimentares usam somente dias com valores registrados. Quantidades diferentes de dias e registros incompletos limitam a interpretação; não representam necessariamente todo o período. O tempo total só aparece quando todas as sessões têm duração registrada.')}`:note('Todo o histórico mostra trajetórias. Escolha 30 dias, 90 dias ou 1 ano para comparar dois períodos de igual duração.')}</section>`;
}
function bodySection(m){
  const b=m.body;
  return `<section class="ltsReportSection" id="reportComposition"><h2>Peso, músculo e gordura</h2>${select('reportBodySource','Origem das medições',b.origins,b.selection,true)}<div class="ltsReportCharts">${metricDefs.map(([key,label,unit,digits])=>{const points=b.series[key]||[];return `<article><h3>${label}</h3><p class="ltsReportValue">${value(points.at(-1)?.value,unit,digits)}<small>${points.length?fmtDate(points.at(-1).date):'Sem medição no período'}</small></p>${contextChart(points,{label,unit,digits,bounds:m.current,selectable:false})}</article>`;}).join('')}</div>${b.available?note(`Comparação ${fmtDate(b.start)} → ${fmtDate(b.end)}: ${metricDefs.map(([key,label,unit])=>`${label.toLowerCase()} ${delta(b.changes[key],key==='body_fat_pct'?'p.p.':unit)}`).join(' · ')}.`):note(reason(b.reason))}${note('Linhas seguem a origem e o aparelho registrados. Modelo não informado permanece identificado; a comparação descreve valores, não garante uma mudança biológica.')}</section>`;
}
function segmentSection(m){
  const s=m.segmental,label=segments.find(([k])=>k===s.region)?.[1]||'Segmento',metric=s.metric==='fat'?'Massa de gordura':'Massa magra';
  return `<section class="ltsReportSection" id="reportSegmental"><h2>Onde o corpo mudou</h2><div class="ltsReportControls">${select('reportRegion','Segmento',segments.map(([k,l])=>[k,l]),s.region)}${select('reportSegmentMetric','Medida',[['lean','Massa magra'],['fat','Massa de gordura']],s.metric)}${select('reportSegmentSource','Origem segmentar',s.origins,s.selection,true)}</div>${contextChart(s.points,{label:`${metric} · ${label}`,unit:'kg',digits:2,bounds:m.current,selectable:false})}${s.available?note(`Comparação ${fmtDate(s.start)} → ${fmtDate(s.end)}. O contexto de treino abaixo usa os dias entre essas medições.`):note(reason(s.reason))}<div class="ltsReportTableWrap"><table class="ltsReportTable"><thead><tr><th>Segmento</th><th>Massa magra · kg</th><th>Gordura · kg</th><th>Δ magra · kg</th><th>Δ gordura · kg</th></tr></thead><tbody>${s.parts.map(p=>`<tr><th scope="row">${esc(p.label)}</th><td>${value(p.current,'',2)}</td><td>${value(p.fat,'',2)}</td><td>${delta(p.delta,'',2)}</td><td>${delta(p.fatDelta,'',2)}</td></tr>`).join('')}</tbody></table></div>${s.latest?note(`Valores da medição em ${fmtDate(s.latest.measured_at)}. Diferenças aparecem somente quando há uma base comparável.`):''}${s.available?`<div class="ltsReportContext"><h3>Treino e alimentação entre medições</h3><p>${s.training?.sessions==null?'Treino regional indisponível':`${s.training.sessions} sessões e ${s.training.sets==null?'séries não disponíveis':`${s.training.sets} séries registradas`} com ${s.training.groups.length?esc(s.training.groups.join(', ')):'grupos desta região'}`}. ${s.nutrition?.counts.protein_g?`Proteína: ${value(s.nutrition.means.protein_g,'g',0)} por dia registrado; ${s.nutrition.counts.protein_g} de ${s.nutrition.intervalDays} dias têm valor.`:'Não há cobertura alimentar para proteína nesse intervalo.'}</p><button data-route="treinos">Consultar exercícios e cargas ›</button></div>`:''}<details class="ltsReportMethod"><summary>Como interpretar a bioimpedância</summary><p>Massa magra segmentar inclui água e outros tecidos; não é uma medida direta de músculo. Hidratação, exercício recente e condições da medição podem alterar as estimativas. Uma mudança isolada merece confirmação em condições comparáveis antes de orientar ajustes.</p><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC11649400/" target="_blank" rel="noopener noreferrer">Estudo de repetibilidade e variabilidade da bioimpedância</a></details></section>`;
}
function labsSection(m){
  const l=m.labs,selected=l.selected,points=l.points,point=points[Number(state.ui.reportLabPoint)]||points.at(-1),query=norm(state.ui.reportLabQuery||'');
  const list=l.comparisons.filter(r=>!query||norm(r.group.label).includes(query)),page=pageOf(list,state.ui.reportLabPage,10);
  const comparisonReason=r=>r.reason==='unknown_method'?'Método não informado':r.reason==='incompatible'?'Origem, unidade ou método diferente':r.reason==='non_exact'?'Resultado sem valor numérico exato':r.reason==='ambiguous'?'Mais de um resultado nesta data':'Sem anterior comparável no período';
  return `<section class="ltsReportSection" id="reportLabs"><h2>Exames ao longo do tempo</h2>${select('reportLabMarker','Marcador',l.groups.map(g=>[g.key,g.label]),selected?.group.key)}${selected?.current?`<p class="ltsReportValue">${esc(labResultText(selected.current))}<small>${fmtDate(selected.current.collection_date)} · ${esc(selected.current.laboratory||selected.current.source)}</small></p>`:''}${contextChart(points,{label:selected?.group.label||'Exames',unit:l.unit,digits:2,bounds:m.current,selectable:false})}${points.length?`${select('reportLabPoint','Consultar ponto',points.map((p,i)=>[String(i),`${fmtDate(p.date)} · ${p.context}`]),String(points.indexOf(point)))}<div class="ltsReportContext" role="status"><b>${esc(selected?.group.label)}: ${esc(labResultText(point.row))}</b><p>${fmtDate(point.date)} · ${esc(point.context)}<br>Referência informada: ${esc(point.row.reference_range||'Não registrada')}</p></div>`:''}${selected?.comparable?note(`Anterior comparável: ${labResultText(selected.previous)} em ${fmtDate(selected.previous.collection_date)}. Diferença: ${delta(selected.delta,l.unit,2)}. Mesma origem, unidade e método registrados.`):selected?note(comparisonReason(selected)):empty('Não há exame nesta janela.')}${note('Pontos preservam as datas reais. Métodos desconhecidos ficam sem linha; origens e métodos diferentes não são unidos. Resultados textuais e limites continuam disponíveis na tabela e no histórico de Exames.')}<label class="ltsField">Buscar comparação<input id="reportLabQuery" data-report-search type="search" value="${esc(state.ui.reportLabQuery||'')}" placeholder="Nome do marcador" autocomplete="off"></label><div class="ltsReportTableWrap"><table class="ltsReportTable"><thead><tr><th>Marcador</th><th>Atual no período</th><th>Anterior no período</th><th>Diferença / limite</th></tr></thead><tbody>${page.rows.map(r=>`<tr><th scope="row"><button data-report-marker="${esc(r.group.key)}">${esc(r.group.label)}</button></th><td>${r.current?esc(labResultText(r.current)):'Em revisão'}<small>${r.current?fmtDate(r.current.collection_date):''}</small></td><td>${r.previous?esc(labResultText(r.previous)):'Sem anterior'}<small>${r.previous?fmtDate(r.previous.collection_date):''}</small></td><td>${r.comparable?esc(delta(r.delta,r.current.unit,2)):esc(comparisonReason(r))}</td></tr>`).join('')}</tbody></table></div>${pager(page,'reportLabPage').replaceAll('data-depth-page','data-report-page')}<button data-route="saude">Abrir todas as coletas e referências ›</button></section>`;
}
function trainingRecovery(m){
  const r=m.recovery,label=r.selected?`${signalLabels[r.selected.metric]} · ${r.selected.label}`:'Recuperação';
  return `<section class="ltsReportSection"><h2>Treino e recuperação na mesma janela</h2><div class="ltsReportCharts"><article><h3>Tempo de treino registrado</h3>${contextChart(m.training.points,{label:'Tempo de treino registrado',unit:'min',digits:0,bounds:m.current,bar:true,selectable:false})}${note(m.lastWorkout?`Última sessão confirmada: ${fmtDate(m.lastWorkout)}. Dias sem registro não significam descanso confirmado.`:'Sem sessão confirmada no histórico carregado.')}</article><article><h3>Recuperação por origem</h3>${select('reportRecoverySource','Sinal e aparelho/origem',r.series.map(s=>[s.key,`${signalLabels[s.metric]} · ${s.label} · ${s.unit}`]),r.selected?.key)}${contextChart(r.points,{label,unit:r.selected?.unit||'',digits:1,bounds:m.current,selectable:false})}</article></div>${r.selected?note(`${label}. Cada série mantém unidade e origem próprias. Valores são observações preservadas; alterações não são classificadas automaticamente como melhora ou piora.`):note('Não há sinal de recuperação dessa origem na janela. A conexão Polar poderá preencher os próximos registros depois da autorização e validação.')}</section>`;
}
export function renderUsefulReports(){
  const m=usefulReports(state.data,state.domainStatus,state.ui),failures=['body','segmental','nutrition','labs','workouts','exercises','sets','sourceMetrics','polarSessions'].filter(k=>state.domainStatus[k]==='error');
  return `<div class="ltsUsefulReports">${screenTitle('Recuperação & análises','Comparações históricas e contexto para discutir com seu treinador e seu médico.','Relatórios & insights')}<div class="ltsReportHeader"><label class="ltsField">Janela do relatório<select id="analysisPeriod">${[['30','30 dias'],['90','90 dias'],['365','1 ano'],['all','Todo o histórico']].map(([k,l])=>`<option value="${k}" ${k===m.period?'selected':''}>${l}</option>`).join('')}</select></label><p>${esc(range(m.current))}<small>Janela termina hoje; cada observação mantém sua data.</small></p></div>${failures.length?empty('Parte dos dados não carregou. As comparações dessas áreas ficam bloqueadas; as demais continuam disponíveis.'):''}${findings(m)}${periodComparison(m)}${bodySection(m)}${segmentSection(m)}${labsSection(m)}${trainingRecovery(m)}${polarSection(m)}<p class="ltsReportNote">Achados baseados em regras e registros, sem diagnóstico, prescrição ou ajuste automático de treino e medicações. As perguntas de investigação orientam a conversa com seus profissionais.</p></div>`;
}
function polarSection(m){
  if(state.domainStatus.polarSessions==='error')return `<section class="ltsReportSection"><h2>Treinos recebidos do Polar</h2>${empty('As sessões Polar não carregaram. Elas não foram substituídas por sessões de outra origem.')}</section>`;
  if(!m.polar.rows.length)return '';
  const page=pageOf([...m.polar.rows].reverse(),state.ui.reportPolarPage,8);
  return `<section class="ltsReportSection" id="reportPolar"><h2>Treinos recebidos do Polar</h2>${contextChart(m.polar.points,{label:'Tempo registrado no Polar',unit:'min',digits:0,bounds:m.current,bar:true,selectable:false})}${note('São sessões registradas na conta Polar, apresentadas separadamente dos treinos de musculação confirmados. Um mesmo treino pode aparecer nas duas origens; os totais não são somados. Aparelhos numerados têm identificadores distintos, sem modelo informado.')}<div class="ltsReportTableWrap"><table class="ltsReportTable"><thead><tr><th>Sessão</th><th>Data e origem</th><th>Duração</th><th>FC média / máxima</th></tr></thead><tbody>${page.rows.map(r=>`<tr><th scope="row">${esc(r.session_name)}</th><td>${fmtDate(r.workout_date)}<small>${esc(r.displaySource)}</small></td><td>${value(r.duration_minutes,'min',1)}</td><td>${value(r.heart_rate_avg,'bpm',0)} / ${value(r.heart_rate_max,'bpm',0)}</td></tr>`).join('')}</tbody></table></div>${pager(page,'reportPolarPage').replaceAll('data-depth-page','data-report-page')}</section>`;
}
